<div class="container">
	<br>
	<?php View::content() ?>
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Mi Perfil</h3>
	  </div>
	  <div class="panel-body">
	    <label>Email: </label>
	    <?php echo $user->email ?>
	    <hr>
	    <?php echo Form::open() ?>
	    <div class="form-group">
	    	<label>Cambiar Contraseña: </label>
	    	<input type="password" name="passanterior" placeholder="Contraseña Anterior" class="form-control">
	    	<input type="password" name="passnueva" class="form-control" placeholder="Contraseña Nueva">
	    </div>
	    <input type="submit" value="Cambiar" class="btn btn-success btn-xs">
	    <?php echo Form::close() ?>

	  </div>
	</div>
</div>