<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title>Kumbia-librerias-acl</title>
  <?php Tag::css("bootstrap/css/bootstrap.min") ?>
  <?php echo Html::includeCss() ?>
  <?php echo Tag::js("jquery/jquery.min") ?>
  <?php echo Tag::js("bootstrap/js/bootstrap.min") ?>
</head>
<body>
  <div id='content'>
    <?php View::content(); ?>
  </div>
</body>
</html>
