<div class="container">
	<br>
	<?php View::content() ?>
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">Login</h3>
	  </div>
	  <div class="panel-body">
	    <?php echo Form::open() ?>
		<div class="form-group">
			<label for="">Email:</label>
			<input type="email" name="email" class="form-control">
		</div>
		<div class="form-group">
			<label for="">Contraseña:</label>
			<input type="password" name="pass" class="form-control">
		</div>
		<input type="submit" class="btn btn-success btn-xs" value="Entrar">
		<?php echo Html::link("user/nuevo","Crear Usuario","class='btn btn-info btn-xs'")?>
		<?php echo Form::close() ?>
	  </div>
	</div>
</div>